apiVersion: v1
kind: Secret
metadata:
  name: shlomo-secret
  namespace: sh-z-wind-dev
type: Opaque
stringData:
  username: "IRGC"
  password: "iraniraniran"
  db_name: "IranMalDB"
  collection_name: "tweets"
  mongo_url: "mongodb+srv://IRGC:iraniraniran@iranmaldb"